# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Kusudamas - Jekyll-based static site and blog
email: kusudama@example.com
description: > # this means to ignore newlines until "baseurl:"
  Kusudama - Jekyll static site template
baseurl: "/kusudama" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: example
tumblr_username: example
facebook_username: example

permalink: /:categories/:title

links:
  - title: about
    url: /about
  - title: projects
    url: /projects
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me

# Build settings
markdown: kramdown
